# Generated by Django 3.2.8 on 2021-10-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
